# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp1 <- function(inputn, inputp, inputQ, inputtype) {
    .Call('svspm_cpp1', PACKAGE = 'svspm', inputn, inputp, inputQ, inputtype)
}

cpp2 <- function(inputn, inputp, inputQ, inputtype, method) {
    .Call('svspm_cpp2', PACKAGE = 'svspm', inputn, inputp, inputQ, inputtype, method)
}

cpp3 <- function(y, maxiter, Nb) {
    .Call('svspm_cpp3', PACKAGE = 'svspm', y, maxiter, Nb)
}

cpp4 <- function(y, p, Q, maxiter, Nb) {
    .Call('svspm_cpp4', PACKAGE = 'svspm', y, p, Q, maxiter, Nb)
}

cpp5 <- function(y, p, Q, maxiter, Nb) {
    .Call('svspm_cpp5', PACKAGE = 'svspm', y, p, Q, maxiter, Nb)
}

cpp6 <- function(y, p, Q, wdp, maxiter, Nb) {
    .Call('svspm_cpp6', PACKAGE = 'svspm', y, p, Q, wdp, maxiter, Nb)
}

cpp7 <- function(Macf, Szacf, Snacf, Wacf, psiacf, fiacf, Mu0acf, len, tsize) {
    .Call('svspm_cpp7', PACKAGE = 'svspm', Macf, Szacf, Snacf, Wacf, psiacf, fiacf, Mu0acf, len, tsize)
}

