// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cpp1
arma::vec cpp1(double inputn, double inputp, double inputQ, double inputtype);
RcppExport SEXP svspm_cpp1(SEXP inputnSEXP, SEXP inputpSEXP, SEXP inputQSEXP, SEXP inputtypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type inputn(inputnSEXP);
    Rcpp::traits::input_parameter< double >::type inputp(inputpSEXP);
    Rcpp::traits::input_parameter< double >::type inputQ(inputQSEXP);
    Rcpp::traits::input_parameter< double >::type inputtype(inputtypeSEXP);
    __result = Rcpp::wrap(cpp1(inputn, inputp, inputQ, inputtype));
    return __result;
END_RCPP
}
// cpp2
arma::vec cpp2(double inputn, double inputp, double inputQ, double inputtype, double method);
RcppExport SEXP svspm_cpp2(SEXP inputnSEXP, SEXP inputpSEXP, SEXP inputQSEXP, SEXP inputtypeSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type inputn(inputnSEXP);
    Rcpp::traits::input_parameter< double >::type inputp(inputpSEXP);
    Rcpp::traits::input_parameter< double >::type inputQ(inputQSEXP);
    Rcpp::traits::input_parameter< double >::type inputtype(inputtypeSEXP);
    Rcpp::traits::input_parameter< double >::type method(methodSEXP);
    __result = Rcpp::wrap(cpp2(inputn, inputp, inputQ, inputtype, method));
    return __result;
END_RCPP
}
// cpp3
Rcpp::List cpp3(arma::vec y, double maxiter, double Nb);
RcppExport SEXP svspm_cpp3(SEXP ySEXP, SEXP maxiterSEXP, SEXP NbSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type Nb(NbSEXP);
    __result = Rcpp::wrap(cpp3(y, maxiter, Nb));
    return __result;
END_RCPP
}
// cpp4
Rcpp::List cpp4(arma::vec y, int p, int Q, double maxiter, double Nb);
RcppExport SEXP svspm_cpp4(SEXP ySEXP, SEXP pSEXP, SEXP QSEXP, SEXP maxiterSEXP, SEXP NbSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type Q(QSEXP);
    Rcpp::traits::input_parameter< double >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type Nb(NbSEXP);
    __result = Rcpp::wrap(cpp4(y, p, Q, maxiter, Nb));
    return __result;
END_RCPP
}
// cpp5
Rcpp::List cpp5(arma::vec y, int p, int Q, double maxiter, double Nb);
RcppExport SEXP svspm_cpp5(SEXP ySEXP, SEXP pSEXP, SEXP QSEXP, SEXP maxiterSEXP, SEXP NbSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type Q(QSEXP);
    Rcpp::traits::input_parameter< double >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type Nb(NbSEXP);
    __result = Rcpp::wrap(cpp5(y, p, Q, maxiter, Nb));
    return __result;
END_RCPP
}
// cpp6
Rcpp::List cpp6(arma::vec y, int p, int Q, int wdp, double maxiter, double Nb);
RcppExport SEXP svspm_cpp6(SEXP ySEXP, SEXP pSEXP, SEXP QSEXP, SEXP wdpSEXP, SEXP maxiterSEXP, SEXP NbSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type Q(QSEXP);
    Rcpp::traits::input_parameter< int >::type wdp(wdpSEXP);
    Rcpp::traits::input_parameter< double >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type Nb(NbSEXP);
    __result = Rcpp::wrap(cpp6(y, p, Q, wdp, maxiter, Nb));
    return __result;
END_RCPP
}
// cpp7
Rcpp::List cpp7(arma::vec Macf, arma::vec Szacf, arma::vec Snacf, arma::vec Wacf, arma::vec psiacf, arma::vec fiacf, arma::vec Mu0acf, double len, double tsize);
RcppExport SEXP svspm_cpp7(SEXP MacfSEXP, SEXP SzacfSEXP, SEXP SnacfSEXP, SEXP WacfSEXP, SEXP psiacfSEXP, SEXP fiacfSEXP, SEXP Mu0acfSEXP, SEXP lenSEXP, SEXP tsizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type Macf(MacfSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Szacf(SzacfSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Snacf(SnacfSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Wacf(WacfSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type psiacf(psiacfSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type fiacf(fiacfSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Mu0acf(Mu0acfSEXP);
    Rcpp::traits::input_parameter< double >::type len(lenSEXP);
    Rcpp::traits::input_parameter< double >::type tsize(tsizeSEXP);
    __result = Rcpp::wrap(cpp7(Macf, Szacf, Snacf, Wacf, psiacf, fiacf, Mu0acf, len, tsize));
    return __result;
END_RCPP
}
